# Generated by Django 5.1.3 on 2024-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_courses_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrequest',
            name='courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
