# Generated by Django 5.1.3 on 2024-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_id', models.JSONField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='chapters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_id',
            field=models.JSONField(default=int),
        ),
    ]
