# Generated by Django 5.1.3 on 2024-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_chapters_subjects_chapters_subjects_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='id',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_id',
            field=models.JSONField(default=int, primary_key=True, serialize=False),
        ),
    ]
