# Generated by Django 5.1.3 on 2024-11-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_subjects_id_alter_subjects_subject_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
