# Generated by Django 5.1.3 on 2024-11-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapters',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
