# Generated by Django 5.1.3 on 2024-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_chapters_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='subjectid',
            field=models.JSONField(blank=True, default=int),
        ),
        migrations.AddField(
            model_name='subjects',
            name='coursename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
