# Generated by Django 5.1.3 on 2024-11-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_chapters_subjectid_subjects_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='subjectid',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='coursename',
        ),
    ]
