# Generated by Django 5.1.3 on 2024-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_remove_chapters_subjectid_remove_courses_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=150, unique=True)),
                ('subject_id', models.JSONField(blank=True, default=int)),
                ('chap_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subjects',
            name='chapters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
