# Generated by Django 5.1.3 on 2024-11-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_testentry_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testentry',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='testentry',
            name='sub_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
