# Generated by Django 5.1.3 on 2024-11-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_testentry_entry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='testentry',
            name='entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
