# Generated by Django 5.1.3 on 2024-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_remove_testentry_id_alter_testentry_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testentry',
            name='chap_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testentry',
            name='coursename',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testentry',
            name='sub_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
