# Generated by Django 5.1.3 on 2024-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_testentry_chap_id_alter_testentry_coursename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.JSONField(blank=True)),
            ],
        ),
    ]
