# Generated by Django 5.1.3 on 2024-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_remove_subjects_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testentry',
            old_name='chap_id',
            new_name='chapname',
        ),
        migrations.RenameField(
            model_name='testentry',
            old_name='sub_id',
            new_name='subname',
        ),
    ]
