# Generated by Django 5.1.3 on 2024-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_rename_chap_id_testentry_chapname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testentry',
            old_name='chapname',
            new_name='chap_id',
        ),
        migrations.RenameField(
            model_name='testentry',
            old_name='subname',
            new_name='sub_id',
        ),
        migrations.AlterField(
            model_name='testentry',
            name='quizzes',
            field=models.JSONField(blank=True, default=object),
        ),
    ]
