# Generated by Django 5.1.3 on 2024-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_rename_chapname_testentry_chap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testentry',
            name='quizzes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
