# Generated by Django 5.1.3 on 2024-11-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_alter_testentry_quizzes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
