# Generated by Django 5.1.3 on 2024-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coursePageName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
