# Generated by Django 5.1.3 on 2024-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=150, unique=True)),
                ('coursename', models.CharField(max_length=150, unique=True)),
                ('subjectname', models.CharField(max_length=150, unique=True)),
                ('chapname', models.CharField(max_length=150, unique=True)),
                ('points', models.JSONField(blank=True, default=int)),
            ],
        ),
    ]
