# Generated by Django 5.1.3 on 2024-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taketest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscores',
            name='chapname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='coursename',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='studentname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='subjectname',
            field=models.CharField(max_length=150),
        ),
    ]
