# Generated by Django 5.1.3 on 2024-11-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taketest', '0002_alter_testscores_chapname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscores',
            name='quizuniqueidenitiy',
            field=models.CharField(default=list, max_length=150),
        ),
    ]
